### ISSUE TITLE
work if the app is dead ?

### ISSUE THREAD

**Issue by medrockstar** [saty932/cordova-plugin-beacon-monitoring-in-background-with-notifications-android#1]
Hi,

The plugin works when the app is totally dead not just closed ?

Tks,

**Comment by saty932** [comment]
You mean when the app is killed right I mean when the app is removed from background right?
When you kill the app then also this plugin works...You will be notified when ever you entered into beacon region

**Comment by medrockstar** [comment]
This work only with android ?

Le 8 févr. 2018 15:30, "sathish bottula" <notifications@github.com> a
écrit :

**Comment by saty932** [comment]
Yes brother...This plugin is for android only.In IOS by default ionic native Ibeacon can trigger the function even if we kill the app.I read somewhere in the blogs but I didn't test..
